/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.Vista;

import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author raulbrun
 */
public class MiCuenta extends javax.swing.JPanel {
    private final vPrincipal vista;
    private VFrame ventana;
    /**
     * Creates new form vPrincipal
     * @param vista
     * @param ventana
     */
    public MiCuenta(vPrincipal vista, VFrame ventana) {
        initComponents();
        this.vista = vista;
        this.ventana = ventana;
        userName.setText(vista.getUsuario().getNombre());
        error1.setVisible(false);
        error2.setVisible(false);
        not_confirmacion.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        userName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        oldPass = new javax.swing.JPasswordField();
        newPass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        error1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonCambio = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        passwdBaja = new javax.swing.JPasswordField();
        error2 = new javax.swing.JLabel();
        botonBaja = new javax.swing.JButton();
        not_confirmacion = new javax.swing.JLabel();

        back.setText("Atrás");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        userName.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        userName.setText("Nombre usuario");

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel1.setText("Cambiar contraseña:");

        oldPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldPassActionPerformed(evt);
            }
        });

        jLabel2.setText("Contraseña actual");

        jLabel3.setText("Nueva contraseña");

        error1.setFont(new java.awt.Font("Noto Sans", 2, 14)); // NOI18N
        error1.setForeground(new java.awt.Color(232, 19, 19));
        error1.setText("La contraseña actual no es correcta");

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel4.setText("Darse de baja: ");

        botonCambio.setText("Cambiar");
        botonCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambioActionPerformed(evt);
            }
        });

        jLabel5.setText("Contraseña para confirmar");

        error2.setFont(new java.awt.Font("Noto Sans", 2, 14)); // NOI18N
        error2.setForeground(new java.awt.Color(232, 19, 19));
        error2.setText("La contraseña actual no es correcta");

        botonBaja.setText("Confirmar");
        botonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBajaActionPerformed(evt);
            }
        });

        not_confirmacion.setFont(new java.awt.Font("Noto Sans", 3, 14)); // NOI18N
        not_confirmacion.setForeground(new java.awt.Color(58, 202, 61));
        not_confirmacion.setText("Contraseña cambiada correctamente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passwdBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(error2))
                            .addComponent(botonBaja)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(botonCambio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(not_confirmacion)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(oldPass)
                                            .addComponent(newPass, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(error1))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(173, 173, 173)
                        .addComponent(userName)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userName))
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(error1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCambio)
                    .addComponent(not_confirmacion))
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(passwdBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonBaja)
                .addContainerGap(129, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        ventana.setContentPane(vista);
        ventana.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void botonCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambioActionPerformed
        try {
            // TODO add your handling code here:
            if(vista.getServidor().changePass(vista.getUsuario().getNombre(), oldPass.getText(), newPass.getText())){
                error1.setVisible(false);
                not_confirmacion.setVisible(true);
            }else{
                not_confirmacion.setVisible(false);
                error1.setVisible(true);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(MiCuenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonCambioActionPerformed

    private void oldPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldPassActionPerformed

    private void botonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBajaActionPerformed
        try {
            // TODO add your handling code here:
            if(vista.getServidor().bajaUsuario(userName.getText(),passwdBaja.getText())){
                Login lG = new Login(vista.getServidor(), ventana);
                ventana.setContentPane(lG);
                ventana.setVisible(true);
            }else{
                error2.setVisible(true);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(MiCuenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonBajaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton botonBaja;
    private javax.swing.JButton botonCambio;
    private javax.swing.JLabel error1;
    private javax.swing.JLabel error2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField newPass;
    private javax.swing.JLabel not_confirmacion;
    private javax.swing.JPasswordField oldPass;
    private javax.swing.JPasswordField passwdBaja;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
